sudo: required
services:
  - docker  # Required to run docker commands

before_install:
  - docker build -t simplefrontend -f Dockerfile.dev .

script:
  - docker run -e CI=true simplefrontend npm run test -- --coverage